tunnel: tsbrs-tunnel
credentials-file: ./credentials.json
ingress:
  - hostname: tsbrs-${RANDOM_ID}.trycloudflare.com  # ← Cloudflare will auto-generate
    service: http://localhost:5000
  - service: http_status:404